### PR TITLE
Update github.com/oleiade/reflections to v1.0.1 to avoid checksum mismatch

### PR DESCRIPTION
**Pull request by dveeden**
See https://github.com/oleiade/reflections/issues/14 for details.

### CODE REVIEW

**Comment by baurine** [comment]
hi @dveeden, thanks for your contribution, the CI doesn't pass, can you check it.

**Comment by breeswish** [comment]
Thank you for your contribution! The CI failed due to some linter problems. I guess it is not related to your change and I will take a look.

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
I managed to fix the CI build error after cleaning up the `go.sum`.

**Comment by breeswish** [comment]
Note: for people that facing build failures due to reflection commit change, you are likely to use GOPPROXY=direct. In order to migrate the issue, you can also try with something like:

```go
GOPROXY=https://proxy.golang.org make
```

**Comment by TisonKun** [comment]
> Note: for people that facing build failures due to reflection commit change, you are likely to use GOPPROXY=direct. In order to migrate the issue, you can also try with something like:
> 
> ```shell
> GOPROXY=https://proxy.golang.org make
> ```

Thanks. It should have saved hours of work.

**Pull request merged**
