### PR TITLE
fix(stmt & slowquery): ignored virtual fields

### PR DESCRIPTION
**Pull request by shhdgit**
Append ignored virtual fields to table_columns api. Then plan_count came back.

image

### CODE REVIEW

**Review by breeswish — APPROVED** [review]
Great! Could you also test whether sorting works for it?

**Comment by shhdgit** [comment]
Yes, it works. Because it's sorted on the client.

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
I think we need some rest and clean up some tech debt! For example, adding some tests.

**Pull request merged**
