### PR TITLE
*: update to golang 1.22

### PR DESCRIPTION
**Pull request by lance6716**

### CODE REVIEW

**Review by mornyx — APPROVED** [review]

**Comment by lance6716** [comment]
@mornyx many lint problems found. Pleaes help me to fix them 😢 You can push commits to this PR

**Comment by lhy1024** [comment]
When will we merge it?

**Comment by lhy1024** [comment]
It seems to be better to update to 1.21, which is consistent with PD

And we can update to 1.23 later

**Comment by baurine** [comment]
Replaced by #1709 , so close this PR first.

**Pull request closed without merging**
