### PR TITLE
Release v2022.01.07.1

### PR DESCRIPTION
**Pull request by shhdgit**
Release Note:

1. Fix cross browser hashtag compatibility https://github.com/pingcap/tidb-dashboard/pull/1123
2. Update the year of copyright https://github.com/pingcap/tidb-dashboard/pull/1124
3. Tweak Top SQL UX https://github.com/pingcap/tidb-dashboard/pull/1122
4. Add E2E test https://github.com/pingcap/tidb-dashboard/pull/1109

### CODE REVIEW

**Comment by shhdgit** [comment]
@breeswish PTAL, thanks!

**Comment by breeswish** [comment]
Will this change cause your frontend to change?
https://github.com/pingcap/tidb/pull/31378

**Comment by shhdgit** [comment]
No.

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
Merged. Please follow up PD updates.

**Pull request merged**
