### PR TITLE
ui: Open statement and slow log in new tab

### PR DESCRIPTION
**Pull request by breeswish**
This is a workaround for https://github.com/pingcap/tidb-dashboard/issues/641 to improve UX without changing too many codebase.

However most ideally we should implement page memorization and bring back "Back" again.

Also fixes https://github.com/pingcap/tidb-dashboard/issues/796

Signed-off-by: Breezewish <me@breeswish.org>

### CODE REVIEW

**Review by baurine — APPROVED** [review]
LGTM

**Comment by baurine** [comment]
Maybe later we can try to use use-swr to help cache the API response.

**Comment by unbyte** [comment]
how about using react-keep-alive?

**Comment by breeswish** [comment]
> how about using react-activation?

Feel free to dig it!

**Pull request merged**
