### PR TITLE
fix: label of y-axis is overflow

### LINKED ISSUE #890: QPS Data Over 100K got trimmed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**
Data on Y-AXis is trimmed and incorrect on the page Overview --> QPS Chart
Data over 100K QPS, the right part of the legend data is trimmed.

**What did you expect to see?**

Correct data on Y-AXis

**What did you see instead?**

All the data point on Y-AXis  is 0, the number is trimmed.

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
TiDB Dashboard Internal Version: 2021.03.19.1
TiDB Dashboard Build Git Hash: 2baddeb3c504
TiDB Dashboard Build Time: 2021-04-15 08:06:26
TiDB Dashboard Run in Standalone Mode: NO
PD Version: v4.0.0-rc.2-512-gb8c3d144

image

### PR DESCRIPTION
**Pull request by unbyte**
fix #890 

image

### CODE REVIEW

**Review by breeswish — COMMENTED** [review]
Hmm. Interesting! Why will it work by even reducing the space?

**Comment by unbyte** [comment]
with `grid.containLabel=true`, echarts will take the width of the label into account when rendering

**Pull request merged**
