### PR TITLE
feat(statements): show `plan_cache_hits` field

### LINKED ISSUE #1595: Show `PLAN_CACHE_HITS` field on the SQL statements page
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently on the SQL statements page, `PLAN_CACHE_HITS` is not displayed:

image

But this field exists in the `STATEMENT SUMMARY` table and it can help us know which SQLs cannot hit the plan cache:
img_v2_2a0042f4-46bd-46a0-bb9e-2d2a9555feeg

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by baurine**
close #1595 

## Preview

image

image

### CODE REVIEW

**Comment by baurine** [comment]
@shhdgit @mornyx , PTAL, thanks~

/cc @qw4990

**Comment by baurine** [comment]
Need to show in the detail page as well.

**Review by mornyx — APPROVED** [review]

**Review by shhdgit — APPROVED** [review]
lgtm.

**Pull request merged**
