### PR TITLE
profiling: Pass the TLS certificate to jeprof

### PR DESCRIPTION
**Pull request by Connor1996**
Fix https://github.com/pingcap/tidb-dashboard/issues/1613

Fix it by passing the TLS certificate to jeprof. 

By the way, fix some potential issues in jeprof:
- Join the port to jeprof temporarily file name, otherwise multiple instances deployed in the same host may write to same temp file
- Clean up collected profile files when finished instead of keeping them

Manual Test:
8e6e2b17-272f-44e0-a64f-9a52f3c3de28

### CODE REVIEW

**Comment by Connor1996** [comment]
PTAL @mornyx

**Review by mornyx — APPROVED** [review]

**Comment by mornyx** [comment]
Thanks @Connor1996. Does ngm require the same modification? https://github.com/pingcap/ng-monitoring/tree/main/component/conprof/jeprof

**Comment by Connor1996** [comment]
> Thanks @Connor1996. Does ngm require the same modification? https://github.com/pingcap/ng-monitoring/tree/main/component/conprof/jeprof

Yes

**Pull request merged**
