### PR TITLE
top_sql: experimental implement

### PR DESCRIPTION
**Pull request by shhdgit**
Experimental support for top sql, usage: `bin/tidb-dashboard --experimental`

- [x] UI & API
- [x] Unify UI with tidb dashboard
- [x] Usability
- [ ] Dependencies analysis, optimization

image

### CODE REVIEW

**Comment by shhdgit** [comment]
TODO: dependency analysis, optimization

**Comment by breeswish** [comment]
Seems that there are several things to do to reach a MVP:

1. The Top SQL UI is not unified with the rest. Including paddings, titles, time selection, how controllers are presented, how chart is displayed, etc.
2. The Top SQL UI's usability: Including monospace, expanding SQL full text, column selection and so on.
2. Engineering: dependencies and so on.

Could you continue improving these part and then mark this PR as ready for review?

**Comment by shhdgit** [comment]
Yeah, sure.

I found that the paddings, titles, controllers of KeyViz's fits well with the top sql. But how to display charts is more appropriate.

**Comment by shhdgit** [comment]
For better review experience, split PR to #1091 & #1092.

**Pull request closed without merging**
