### PR TITLE
update etcd to 3.5.15

### PR DESCRIPTION
**Pull request by lhy1024**
It can be reviewed after https://github.com/pingcap/tidb-dashboard/pull/1709 merged

ref https://github.com/tikv/pd/issues/3877

### CODE REVIEW

**Comment by wuhuizuo** [comment]
will we request to upgrade the etcd server? I thinks the client version should keep same with the server version we recommend to deploy.

**Comment by wuhuizuo** [comment]
> will we request to upgrade the etcd server? I thinks the client version should keep same with the server version we recommend to deploy.

And the PD also need to upgrade etcd if it does. and the `ectdctl` binary in release artifacts.

**Comment by lhy1024** [comment]
> will we request to upgrade the etcd server? I thinks the client version should keep same with the server version we recommend to deploy.

Yes, I am trying for it https://github.com/tikv/pd/pull/8441

**Comment by wuhuizuo** [comment]
/hold
it should merge to master after release-8.3 created.

**Comment by lhy1024** [comment]
/unhold
https://github.com/tikv/pd/tree/release-8.3 has been created cc @wuhuizuo 
PTAL @baurine @mornyx

**Review by baurine — APPROVED** [review]

**Pull request merged**
